spring:
  datasource:
    url: jdbc:mysql://rm-uf6g5814m39g10u95.mysql.rds.aliyuncs.com/test_mall?autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=true
    password: wO9jvo1159al
    username: test_mall
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      enable: true
      initial-size: 20
      max-active: 50
      min-idle: 10
      max-wait: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 180000
      max-evictable-idle-time-millis: 300000
      validation-query: SELECT 'X'
      validation-query-timeout: 180
      filters: wall,stat,sl4j2
      db-type: mysql
      async-init: true
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: root
        reset-enable: false
        allow: 192.168.1.153
      web-stat-filter:
        enabled: true
      filter:
        wall:
          config:
            drop-table-allow: false
            multi-statement-allow: true
