spring:
  datasource:
    url: jdbc:mysql://rm-uf6g5814m39g10u95.mysql.rds.aliyuncs.com/prd_mall?autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=true
    password: nO0jv91gsaK
    username: prd_mall
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      enable: true
      initial-size: 20
      max-active: 50
      min-idle: 10
      max-wait: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 180000
      max-evictable-idle-time-millis: 300000
      validation-query: SELECT 'X'
      validation-query-timeout: 180
      filters: wall,stat,sl4j2
      db-type: mysql
      async-init: true
      filter:
        wall:
          config:
            multi-statement-allow: true
            drop-table-allow: false
